dist: trusty
sudo: required
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
language: node_js
node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
cache:
  npm: true
script:
- npm run lint
